### PR TITLE
Add hiera 5 backend

### PR DESCRIPTION
**Pull request by edestecd**
This restores hiera functionality in puppet 4.10/hera 5

### CODE REVIEW

**Comment by dalen** [comment]
Thanks for the contribution, this seems nice. I'm away at a conference at the moment though, but will take a closer look once after that and get back to you.

**Comment by edestecd** [comment]
I did some clean up and added a sort option. Not sure if the sort should just be applied, but it seemed nice to make it optional...

**Comment by mmerfort** [comment]
What's the status for this PR? I would really like to use the hiera backend.

**Comment by bastelfreak** [comment]
Hi @dalen, can you take a look at this again?

**Comment by pietervogelaar** [comment]
+1 I really need this

**Comment by pietervogelaar** [comment]
When will this be merged?

**Comment by pietervogelaar** [comment]
I merged this to my own fork and I can confirm this works beautifully! Thanks a lot @edestecd !!

**Comment by pietervogelaar** [comment]
One addition, In my opinion sort should be default TRUE

**Comment by geekyfox90** [comment]
+1 When a new release would be created ?

**Comment by dalen** [comment]
Sorry about the huge delay on this :( Merging now and will release a new version soon.

I agree it would make sense to sort by default.

**Comment by edestecd** [comment]
I'm not opposed to sorting by default. I would just need notice, so I could change my hiera.

**Pull request merged**
